name: Release new version
on:
  workflow_dispatch:

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '1.4.192'
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.12.0.1479
          bb: 1.4.192

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: bb run test

      - name: Pre-release
        run: bb run pre-release

      - name: Tag+version
        id: tag
        run: |
          version=$(cat VERSION)
          tag=v${VERSION}
          message="new version ${version}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add VERSION
          git commit -m "new version ${version}"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
          echo "TAG=$tag" >> $GITHUB_OUTPUT

      - name: Build all (jar+native)
        run: bb run build-all

      - name: Create a Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          release_name: ${{ steps.tag.outputs.TAG }}

      - name: Upload jar
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar

      - name: Upload native
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.tar.gz

      - name: Post Release
        run: bb run post-release

      - name: Get next version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: 🤖
          file_pattern: VERSION
          commit_message: new version ${{ env.VERSION }}
